version: 1.0.{build}

configuration: Debug
test: on
build:
  project: SlackAPI/SlackAPI.csproj
  publish_nuget: true
  publish_nuget_symbols: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


# scripts to run before build
before_build: nuget restore